version: '3.8'

services:
  app:
    container_name: jangshinnam
    image: jiyoon0221/jangshinnam:latest
    restart: always
    ports:
      - "443:443"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - my_network

networks:
  my_network:
    driver: bridge